FlashcardsApp/Controllers/FlashcardCollectionController.cs
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Text.RegularExpressions;
using FlashcardsApp.CustomExceptions;
using FlashcardsApp.Data;
using FlashcardsApp.Models;
using FlashcardsApp.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace FlashcardsApp.Controllers
{
    [Authorize]
    public class FlashcardCollectionController : Controller
    {
        private readonly HttpClient _httpClient;

        public FlashcardCollectionController(IHttpClientFactory httpClientFactory)
        {
            _httpClient = httpClientFactory.CreateClient("FlashcardsAPI");
        }

        public IActionResult Index(string? sortByCategory = null, string? search = null)
        {
            List<FlashcardCollection<Flashcards>>? flashcardCollections;
            try
            {
                flashcardCollections = HttpApiService.GetFromAPI<List<FlashcardCollection<Flashcards>>>(_httpClient, "/FlashcardCollections/GetFlashcardCollections");

                if (flashcardCollections == null)
                {
                    throw new FlashcardsControllerException("Failed to fetch a flashcard collection.", HttpStatusCode.BadRequest);
                }
            }
            catch (Exception ex)
            {
                return HandleException(ex);
            }

            flashcardCollections.Sort();

            TempData["LastSearchQuery"] = null;

            foreach (var collection in flashcardCollections)
            {
                collection.ReactionCounts = CalculateReactionCounts(collection.Reactions);
            }


            Func<FlashcardCollection<Flashcards>, bool> categoryFilter = (fc) =>
            {
                return string.IsNullOrEmpty(sortByCategory) || fc.Category.ToString() == sortByCategory;
            };

            flashcardCollections = flashcardCollections.Where(categoryFilter).ToList();

            ViewBag.CurrentSort = sortByCategory;

            return View(flashcardCollections);

        }


        public IActionResult CreateFlashcardCollection()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateFlashcardCollection(FlashcardCollection<Flashcards> collection)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    HttpResponseMessage resp = HttpApiService.PostToAPI(_httpClient, "/FlashcardCollections/PostFlashcardCollections", collection);

                    if (resp.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                   
                    throw new FlashcardsControllerException("Failed to create a flashcard collection.", HttpStatusCode.BadRequest);
                }

                return View(collection);
            }
            catch (Exception ex)
            {
                return HandleException(ex);
            }
        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            FlashcardCollection<Flashcards>? collection = HttpApiService.GetFromAPI<FlashcardCollection<Flashcards>>(_httpClient, "/FlashcardCollections/GetFlashcardCollections/", id);

            if (collection == null)
            {
                return RedirectToAction("Index");
            }

            return View(collection);
        }

        [HttpPost]
        public IActionResult RenameCollection(FlashcardCollection<Flashcards> cardCollection)
        {
            FlashcardCollection<Flashcards>? collection = HttpApiService.GetFromAPI<FlashcardCollection<Flashcards>>(_httpClient, "/FlashcardCollections/GetFlashcardCollections/" + cardCollection.Id);

            collection.CollectionName = cardCollection.CollectionName;

            HttpResponseMessage response = HttpApiService.PutToAPI(_httpClient, "/FlashcardCollections/PutFlashcardCollection", collection);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Edit", new { id = cardCollection.Id });
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult AddFlashcard(FlashcardCollection<Flashcards> cardCollection, string NewFlashcardFrontSide, string NewFlashcardBackSide)
        {
            FlashcardCollection<Flashcards>? collection = HttpApiService.GetFromAPI<FlashcardCollection<Flashcards>>(_httpClient, "/FlashcardCollections/GetFlashcardCollections/", cardCollection.Id);

            if (collection != null)
            {
                var newFlashcard = new Flashcards
                {
                    Question = NewFlashcardFrontSide,
                    Answer = NewFlashcardBackSide,
                    FlashcardCollectionId = collection.Id
                };

                HttpResponseMessage response = HttpApiService.PostToAPI(_httpClient, "/Flashcards", newFlashcard);

                if (response.IsSuccessStatusCode)
                    return RedirectToAction("Edit", new { id = collection.Id });
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult AddFlashcardsFromFile(FlashcardCollection<Flashcards> cardCollection, IFormFile? flashcardFile)
        {
            FlashcardCollection<Flashcards>? collection = HttpApiService.GetFromAPI<FlashcardCollection<Flashcards>>(_httpClient, "/FlashcardCollections/GetFlashcardCollections/", cardCollection.Id);

            if (collection == null || flashcardFile == null || flashcardFile.Length < 1)
            {
                return RedirectToAction("Edit", collection);
            }

            FlashcardFileReader fileReader = new();
            List<Flashcards> flashcardsList = fileReader.ReadFromFile(flashcardFile);

            foreach (Flashcards flashcard in flashcardsList)
            {
                flashcard.FlashcardCollectionId = collection.Id;
                HttpApiService.PostToAPI(_httpClient, "/Flashcards", flashcard);
            }

            return RedirectToAction("Edit", collection);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            FlashcardCollection<Flashcards>? collection = HttpApiService.GetFromAPI<FlashcardCollection<Flashcards>>(_httpClient, "/FlashcardCollections/GetFlashcardCollections/", id);

            if (collection == null)
            {
                return NotFound("Collection not found");
            }

            await HttpApiService.DeleteFromAPI(_httpClient, "/FlashcardCollections/DeleteFlashcardCollections/", id);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult ViewCollection(int id)
        {
            var collection = HttpApiService.GetFromAPI<FlashcardCollection<Flashcards>>(_httpClient, "/FlashcardCollections/GetFlashcardCollections/", id);

            if (collection == null)
            {
                return NotFound();
            }

            return View(collection);
        }

        [HttpGet]
        public IActionResult EditFlashcard(int id) 
        {
            Flashcards? flashcard = HttpApiService.GetFromAPI<Flashcards>(_httpClient, "/Flashcards/", id);
            if (flashcard == null)
            {
                return NotFound();
            }
            return View(flashcard);
        }

        [HttpPost]
        public IActionResult EditFlashcard(Flashcards editedFlashcard)
        {
            if (ModelState.IsValid)
            {
                Flashcards? flashcard = HttpApiService.GetFromAPI<Flashcards>(_httpClient, "/Flashcards/", editedFlashcard.Id);

                if (flashcard == null)
                {
                    return NotFound();
                }

                flashcard.Question = editedFlashcard.Question;
                flashcard.Answer = editedFlashcard.Answer;

                HttpApiService.PutToAPI(_httpClient, "/Flashcards/" + flashcard.Id, flashcard);


                return RedirectToAction("Edit", new { id = flashcard.FlashcardCollectionId }); 
            }
            return View(editedFlashcard);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteFlashcard(int id)
        {
            var flashcard = HttpApiService.GetFromAPI<Flashcards>(_httpClient, "/Flashcards/", id);

            if (flashcard == null)
            {
                return NotFound();
            }

            await HttpApiService.DeleteFromAPI(_httpClient, "/Flashcards/", id);

            return RedirectToAction("Edit", new { id = flashcard.FlashcardCollectionId });
        }

        [HttpGet]
        public IActionResult ViewCollections()
        {
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult PlayCollection(int id, int? cardIndex)
        {
            FlashcardCollection<Flashcards>? collection = HttpApiService.GetFromAPI<FlashcardCollection<Flashcards>>(_httpClient, "/FlashcardCollections/GetFlashcardCollections/", id);

            if (collection == null || !collection.Flashcards.Any())
            {
                TempData["ErrorMessage"] = "The selected collection is empty!";
                if (TempData["LastSearchQuery"] != null)
                {
                    string lastSearchQuery = TempData["LastSearchQuery"].ToString();
                    return RedirectToAction("Search", "Home", new { search = lastSearchQuery });
                }

                return RedirectToAction("Index");
            }

            cardIndex ??= 0;
            if (cardIndex < 0) cardIndex = 0;
            if (cardIndex >= collection.Flashcards.Count) cardIndex = collection.Flashcards.Count - 1;

            Flashcards cardToShow = collection.Flashcards.ElementAt((int)cardIndex);

FlashcardsApp/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using FlashcardsApp.Areas.Identity.Data;
using FlashcardsApp.Models;
using System.Threading.Tasks;
using System.Linq;
using FlashcardsApp.Data;
using System.Text;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using Microsoft.AspNetCore.Authorization;
using FlashcardsApp.Services;

namespace FlashcardsApp.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        private readonly UserManager<FlashcardsAppUser> _userManager;
        private readonly IWebHostEnvironment _environment;
        private readonly HttpClient _httpClient;
        private readonly ILogger<ProfileController> _logger;

        public ProfileController(UserManager<FlashcardsAppUser> userManager, IWebHostEnvironment environment, IHttpClientFactory httpClientFactory, ILogger<ProfileController> logger)
        {
            _userManager = userManager;
            _environment = environment;
            _httpClient = httpClientFactory.CreateClient("FlashcardsAPI");
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);
     
            var response = await _httpClient.GetAsync($"api/Profile/{userId}");
            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var profile = JsonConvert.DeserializeObject<Profile>(content);

                var followingCollections = HttpApiService.GetFromAPI<List<FlashcardCollection<Flashcards>>>(_httpClient, "/Followings/GetUsersFollowedByUserWithIdCollections/" + userId);

                return View(new ProfileViewModel() {Profile = profile, FollowingCollections = followingCollections});
            }

            return View("Error");
        }

        [HttpPost]
        public async Task<IActionResult> EditDescription(string description)
        {
            var userId = _userManager.GetUserId(User);
            
            description ??= string.Empty;

            var jsonString = JsonConvert.SerializeObject(description);
            var content = new StringContent(jsonString, Encoding.UTF8, "application/json");
            var response = await _httpClient.PostAsync($"api/Profile/EditDescription?userId={userId}", content);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction(nameof(Index));
            }

            return View("Error");
        }

        [HttpPost]
        public async Task<IActionResult> UploadProfilePhoto(IFormFile profilePhoto)
        {
            _logger.LogInformation("UploadProfilePhoto method called");
            var userId = _userManager.GetUserId(User);
            if (profilePhoto == null || profilePhoto.Length == 0)
            {
                ModelState.AddModelError(string.Empty, "Invalid request.");
                return View("Index");
            }

            var extension = Path.GetExtension(profilePhoto.FileName).ToLower();
            if (extension != ".jpg")
            {
                ModelState.AddModelError(string.Empty, "Only .jpg files are allowed.");
                return View("Index");
            }

            const int maxFileSize = 5 * 1024 * 1024;
            if (profilePhoto.Length > maxFileSize)
            {
                ModelState.AddModelError(string.Empty, "File size cannot exceed 5 MB.");
                return View("Index");
            }

            var uniqueFileName = Guid.NewGuid().ToString() + extension;
            var filePath = Path.Combine(_environment.WebRootPath, "uploads", uniqueFileName);

            try
            {
                var directoryPath = Path.GetDirectoryName(filePath);
                if (!Directory.Exists(directoryPath))
                {
                    Directory.CreateDirectory(directoryPath);
                }

                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await profilePhoto.CopyToAsync(stream);
                }

                var profilePhotoPath = $"uploads/{uniqueFileName}";
                await UpdateProfilePhotoPathInApi(userId, profilePhotoPath);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                ModelState.AddModelError(string.Empty, "Error saving the photo.");
                return View("Index");
            }
        }

        private async Task<bool> UpdateProfilePhotoPathInApi(string userId, string profilePhotoPath)
        {
            string requestUri = $"api/Profile/UploadProfilePhoto?userId={Uri.EscapeDataString(userId)}&profilePhotoPath={Uri.EscapeDataString(profilePhotoPath)}";

            var response = await _httpClient.PostAsync(requestUri, null);

            if (!response.IsSuccessStatusCode)
            {
                _logger.LogError($"API call failed with status code {response.StatusCode} and message: {await response.Content.ReadAsStringAsync()}");
                return false;
            }

            return true;
        }

    }
}

FlashcardsApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using FlashcardsApp.Areas.Identity.Data
@using FlashcardsApp.Extension

@inject SignInManager<FlashcardsAppUser> SignInManager
@inject UserManager<FlashcardsAppUser> UserManager
@{
    var user = await UserManager.GetUserAsync(User);
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FlashcardsApp</title>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FlashcardsApp.styles.css" asp-append-version="true" />
</head>

<body onload="startTimer();">
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="FlashcardCollection" asp-action="Index">Quizmania</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
                    <ul class="navbar-nav" mr-auto>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a> 
                        </li>
                        <li class="nav-item">
@*                             <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
 *@                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FlashcardCollection" asp-action="Index">Feed</a>
                        </li>
                    </ul>
                    <div class="d-flex flex-grow-1 align-items-center justify-content-start mr-3">
                        <form class="form-inline my-2 my-lg-0 flex-grow-1" style="margin-left: 20%; margin-right: 35%;" asp-controller="Home" asp-action="Search" method="get">
                            <input class="form-control rounded-pill flex-grow-1" type="text" name="search" placeholder="Search collections" aria-label="Search">
                        </form>


                        @if (SignInManager.IsSignedIn(User))
                        {
                            <div class="dropdown">
                                <img src="" />
                                <button class="dropdown-toggle" type="button" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="border: none; background:transparent; color: black;">
                                    Hello, @user.FirstName!
                                </button>
                                <div style="margin-right: -25px" class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                                    <a class="dropdown-item" asp-area="" asp-controller="Profile" asp-action="Index">My Profile</a>
                                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Settings</a>
                                    <form asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Content("~/")" method="post" id="logoutForm">
                                        <button type="submit" class="dropdown-item">Logout</button>
                                    </form>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>